CREATE TABLE users (
    user_id int not null generated by default as identity(increment by 1 start 1 
    minvalue 1 maxvalue 2147483647 cache 1),
    first_name varchar(255) not null,
    last_name varchar(255) not null,
    email varchar(255) not null,
    password varchar(255) not null,
    created_at timestamp not null,
    modified_at timestamp not null
);

CREATE TABLE fields_of_law (
    field varchar(255) not null
);

INSERT INTO fields_of_law (field) VALUES 
('Animal'),
('Admiralty'),
('Bankruptcy'),
('Banking & Finance'),
('Civil Rights'),
('Constitutional'),
('Corporate'),
('Criminal'),
('Education'),
('Entertainment'),
('Employment'),
('Environmental & Natural Resources'),
('Family'),
('Health'),
('Immigration'),
('International'),
('Intellectual Property'),
('Military'),
('Personal Injury'),
('Real Estate'),
('Tax');

CREATE TABLE field_of_law_selections (
    id int not null generated by default as identity(increment by 1 start 1 
    minvalue 1 maxvalue 2147483647 cache 1),
    user_id int not null,
    selection_num int not null,
    field_of_law varchar(255) not null,
    years int not null
);

CREATE TABLE achievements (
    id int not null generated by default as identity(increment by 1 start 1 
    minvalue 1 maxvalue 2147483647 cache 1),
    user_id int not null,
    achievements varchar(255) not null
);

